waypoint ckin

diff --git a/fc2-dl b/fc2-dl
--- a/fc2-dl
+++ b/fc2-dl
@@ -34,6 +34,19 @@ find_unique_filename()
     eval "$UNIQUE_FILENAME_VAR=$FILENAME"
 }
 
+purge_temp()
+{
+    if [ $# -ne 1 ]; then
+        echo "Fail! -- Expecting 1 argument! ==> $@"
+        return 1 # non-zero as false
+    fi
+    local TEMP=$1
+    if [ -f $TEMP ]; then
+        echo  "Safely removing temp file ==> $TEMP"
+        rm -f $TEMP
+    fi
+}
+
 if [ $# -ne 1 -a $# -ne 2 ]; then
     echo "Fail! -- Expecting 1 or 2 arguments! ==> $@"
     show_help
@@ -92,7 +105,7 @@ else
 fi
 touch $LOCAL_FILE
 TEMP=${LOCAL_FILE}.part
-trap "rm -f $TEMP" EXIT
+trap "purge_temp $LOCAL_FILE; purge_temp $TEMP" EXIT
 perl -I WWW-FC2Video-Download/lib fc2-dl-core.pl "$UPID" 2 $TEMP
 mv $TEMP $LOCAL_FILE
 
